### ISSUE TITLE
Npm package importing to zombiebox

### ISSUE THREAD

**Issue by officialmmt** [interfaced/zombiebox#13]
Hi there, 

I try to use external npm packages with my project like [m3u parser package](https://www.npmjs.com/package/iptv-playlist-parser). How can I do with easily.  When I try with `import parser from 'iptv-playlist-parser';` that throw 404 error.

**Comment by l1bbcsg** [comment]
Hello!

Generally, you would need to include a browser-ready bundle of a library in `include` config property using `inlineScripts` field, that way the script would be injected with a `<script>` tag and would pollute the global scope with its APIs for you to access them:

```
{
	include: [
		{
			name: 'iptv-playlist-parser',
			inlineScripts: ['/path/to/node_modules/iptv-playlist-parser/dist/index.min.js']
		}
	]
}

```
 
But it seems `iptv-playlist-parser` does not offer a pre-built version, as far as I can see there's only an ES6 index.js, this simply will not work on most TVs even if you find a way to import that file.

I can suggest trying `m3u8-parser` which seem to do the same thing and this is the package we used a few times.
