### ISSUE TITLE
Error initiating package

### ISSUE THREAD

**Issue by hansolowireless** [interfaced/zombiebox#6]
When running npx zombiebox init I get this:

Could not create Application instance, CLI commands that require it will not work: Error: Required by package zombiebox-platform-pc isn't installed.
Install a compatible with range ^2.3.2 version of zombiebox-platform-pc and try again.

Required by zombiebox package zombiebox-platform-pc isn't installed.
Install a compatible with range ^2.3.2 version of zombiebox-platform-pc and try again.

I have already run "npm install zombiebox-platform-pc"

**Comment by l1bbcsg** [comment]
Hello, thanks for trying ZombieBox.

Could you give us exact steps you did to get this error? I couldn't reproduce this on a clean init.

Also adding `--log-level debug` to `zombiebox` CLI might shed some light on what's going on.

From the first message alone it seems weird that the name of package which depends on `zombiebox-platform-pc` is missing as can be seen in [message template](https://github.com/interfaced/zombiebox/blob/28306ef7386133ec0c68ce1e9622e90d4c1d37d1/lib/versions-checker.js#L121) (the `by` part). Could application package.json be malformed?

**Comment by hansolowireless** [comment]
It was indeed a problem with package.json file missing a line. Thanks.
