### ISSUE TITLE
backslashes instead of slashes in base-service-container

### ISSUE THREAD

**Issue by pedrosilvabos** [interfaced/zombiebox#9]
Everytime I start a new zombiebox server(npx zombiebox run), in

./generated/dependency-injection/base-service-container.js

the imports from my scenes are created with a slash instead of a backslash

```javacript
import BaseApplication from "generated/base-application";
import {Home} from "myzombietv\scenes\home\home";
import Player from "myzombietv\scenes\player\player";
import Router from "myzombietv\service\router";
```
I have to correct them manually:
```javacript
import BaseApplication from "generated/base-application";
import {Home} from "myzombietv/scenes/home/home";
import Player from "myzombietv/scenes/player/player";
import Router from "myzombietv/service/router";
```

This was also an issue with the zombiebox-demo.
I am developing in windows environment, not sure if that might be an issue.

**Comment by trave** [comment]
Fixed in related repo.
